# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeleash" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "df7056874f024ca2fb58203dc3392f876037a77002b3aecd552e4d69ff5cd530"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "40b8afb28ad8b0209f001a1364de2b4152f28be0648cf41673aeef19738d0ee7"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e7a67c726832cdd887d20c8d67b4a0e6e99c7689e7999285acb150e575bf4ee1"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8beb9d5b6ff285fc03a4b25a842b8d24bc6c2c429567f37e99de15769536a0ab"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubeleash"
  desc "Kubernetes MCP server that keeps AI agents on a leash"
  homepage "https://github.com/kubeleash/kubeleash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeleash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubeleash"]
    end
  end

  # No zap stanza required

end
