# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeleash" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "471b9f8f9b6e5f2d4e732760e995c0cb0e5a82596c5da511050b45610215f729"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b616391e53fe0be11e90e6ebb1551864ca698e01da70abe3692cd171db88ec92"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f250bcf1457ac579b8ff31294abfceb18e84ae23cec7a9a0f4fd86b13b08a9c7"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1cbfc56f1892765a21c7b1ee30de59135a615c2c8c1392a5788f254763681f3f"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubeleash"
  desc "Kubernetes MCP server that keeps AI agents on a leash"
  homepage "https://github.com/kubeleash/kubeleash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeleash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubeleash"]
    end
  end

  # No zap stanza required

end
