# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeleash" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "00999e838732e2776d6f25bbb93ca5b2f2d860466dee588a5dbee81d1b0e8a52"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c3d853554e8918caf2301f02393ee154c1bf1e70d765722fd708eb4e98eef51"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3404fc822d2275d56f4f8bc4e1c96e198c9f023772a983095afcdf63493d6792"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c672ec2a7f552b6e4169dcfd62d4428e753ba763fa77db1abc37a6b85127a802"
      url "https://github.com/kubeleash/kubeleash/releases/download/v#{version}/kubeleash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubeleash"
  desc "Kubernetes MCP server that keeps AI agents on a leash"
  homepage "https://github.com/kubeleash/kubeleash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeleash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubeleash"]
    end
  end

  # No zap stanza required

end
